package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SERVER_MESSAGE.
 */
public class ServerMessage {

    private Long id;
    private String title;
    private String text;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ServerMessage() {
    }

    public ServerMessage(Long id) {
        this.id = id;
    }

    public ServerMessage(Long id, String title, String text) {
        this.id = id;
        this.title = title;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
