/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.mapsforge.applications.android.samples;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int marker_green=0x7f020000;
        public static final int marker_red=0x7f020001;
    }
    public static final class id {
        public static final int samples=0x7f040000;
    }
    public static final class layout {
        public static final int activity_samples=0x7f030000;
    }
}
