package com.shvil.project.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.shvil.project.db.Angel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ANGEL.
*/
public class AngelDao extends AbstractDao<Angel, Long> {

    public static final String TABLENAME = "ANGEL";

    /**
     * Properties of entity Angel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property City = new Property(1, String.class, "city", false, "CITY");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Phone1 = new Property(3, String.class, "phone1", false, "PHONE1");
        public final static Property Phone2 = new Property(4, String.class, "phone2", false, "PHONE2");
        public final static Property Information = new Property(5, String.class, "information", false, "INFORMATION");
        public final static Property Latitude = new Property(6, long.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(7, long.class, "longitude", false, "LONGITUDE");
        public final static Property Passport = new Property(8, Boolean.class, "passport", false, "PASSPORT");
        public final static Property Stamp = new Property(9, Boolean.class, "stamp", false, "STAMP");
        public final static Property Religious = new Property(10, Boolean.class, "religious", false, "RELIGIOUS");
        public final static Property Distance = new Property(11, Long.class, "distance", false, "DISTANCE");
    };


    public AngelDao(DaoConfig config) {
        super(config);
    }
    
    public AngelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ANGEL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CITY' TEXT NOT NULL ," + // 1: city
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'PHONE1' TEXT NOT NULL ," + // 3: phone1
                "'PHONE2' TEXT," + // 4: phone2
                "'INFORMATION' TEXT," + // 5: information
                "'LATITUDE' INTEGER NOT NULL ," + // 6: latitude
                "'LONGITUDE' INTEGER NOT NULL ," + // 7: longitude
                "'PASSPORT' INTEGER," + // 8: passport
                "'STAMP' INTEGER," + // 9: stamp
                "'RELIGIOUS' INTEGER," + // 10: religious
                "'DISTANCE' INTEGER);"); // 11: distance
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ANGEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Angel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCity());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getPhone1());
 
        String phone2 = entity.getPhone2();
        if (phone2 != null) {
            stmt.bindString(5, phone2);
        }
 
        String information = entity.getInformation();
        if (information != null) {
            stmt.bindString(6, information);
        }
        stmt.bindLong(7, entity.getLatitude());
        stmt.bindLong(8, entity.getLongitude());
 
        Boolean passport = entity.getPassport();
        if (passport != null) {
            stmt.bindLong(9, passport ? 1l: 0l);
        }
 
        Boolean stamp = entity.getStamp();
        if (stamp != null) {
            stmt.bindLong(10, stamp ? 1l: 0l);
        }
 
        Boolean religious = entity.getReligious();
        if (religious != null) {
            stmt.bindLong(11, religious ? 1l: 0l);
        }
 
        Long distance = entity.getDistance();
        if (distance != null) {
            stmt.bindLong(12, distance);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Angel readEntity(Cursor cursor, int offset) {
        Angel entity = new Angel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // city
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // phone1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone2
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // information
            cursor.getLong(offset + 6), // latitude
            cursor.getLong(offset + 7), // longitude
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // passport
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // stamp
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // religious
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // distance
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Angel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCity(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setPhone1(cursor.getString(offset + 3));
        entity.setPhone2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setInformation(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLatitude(cursor.getLong(offset + 6));
        entity.setLongitude(cursor.getLong(offset + 7));
        entity.setPassport(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setStamp(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setReligious(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setDistance(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Angel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Angel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
