/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.shvil.project;

public final class R {
    public static final class anim {
        public static final int animation_enter=0x7f040000;
        public static final int animation_leave=0x7f040001;
        public static final int zoom_enter=0x7f040002;
        public static final int zoom_exit=0x7f040003;
    }
    public static final class array {
        public static final int empty_array=0x7f080000;
        public static final int pref_locale_array=0x7f080003;
        public static final int pref_locale_values_array=0x7f080004;
        public static final int pref_update_freq_array=0x7f080001;
        public static final int pref_update_freq_values_array=0x7f080002;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int padding_large=0x7f060002;
        public static final int padding_medium=0x7f060001;
        public static final int padding_small=0x7f060000;
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int black_white_gradient=0x7f020001;
        public static final int bubble_green=0x7f020002;
        public static final int bubble_yellow=0x7f020003;
        public static final int ic_action_location2=0x7f020004;
        public static final int ic_action_map=0x7f020005;
        public static final int ic_action_mapicon=0x7f020006;
        public static final int ic_action_search=0x7f020007;
        public static final int ic_angel_32=0x7f020008;
        public static final int ic_angel_64=0x7f020009;
        public static final int ic_angel_72=0x7f02000a;
        public static final int ic_bed=0x7f02000b;
        public static final int ic_camera_64=0x7f02000c;
        public static final int ic_launcher=0x7f02000d;
        public static final int ic_map_marker=0x7f02000e;
        public static final int ic_map_marker_48=0x7f02000f;
        public static final int ic_map_people_sun_32=0x7f020010;
        public static final int ic_map_warning_48=0x7f020011;
        public static final int ic_map_warning_64=0x7f020012;
        public static final int ic_menu_location=0x7f020013;
        public static final int ic_menu_location2=0x7f020014;
        public static final int ic_menu_map_icon=0x7f020015;
        public static final int ic_microphone=0x7f020016;
        public static final int ic_my_location_32=0x7f020017;
        public static final int ic_note=0x7f020018;
        public static final int ic_shvil=0x7f020019;
        public static final int ic_water=0x7f02001a;
        public static final int ic_water_carrier=0x7f02001b;
        public static final int location_button=0x7f02001c;
    }
    public static final class id {
        public static final int EditText01=0x7f0b0031;
        public static final int EditText02=0x7f0b0033;
        public static final int EditText03=0x7f0b0038;
        public static final int EditText04=0x7f0b003b;
        public static final int TableRow01=0x7f0b0044;
        public static final int TableRow02=0x7f0b004c;
        public static final int TableRow03=0x7f0b0048;
        public static final int TextView01=0x7f0b0032;
        public static final int TextView02=0x7f0b0034;
        public static final int TextView03=0x7f0b0035;
        public static final int TextView04=0x7f0b0037;
        public static final int TextView05=0x7f0b0039;
        public static final int TextView06=0x7f0b003a;
        public static final int TextView07=0x7f0b004e;
        public static final int TextView08=0x7f0b0050;
        public static final int TextView09=0x7f0b0052;
        public static final int angel_editor_address=0x7f0b0003;
        public static final int angel_editor_information=0x7f0b0009;
        public static final int angel_editor_layout=0x7f0b0001;
        public static final int angel_editor_menu_save=0x7f0b0053;
        public static final int angel_editor_name=0x7f0b0002;
        public static final int angel_editor_passport=0x7f0b0007;
        public static final int angel_editor_phone1=0x7f0b0004;
        public static final int angel_editor_phone2=0x7f0b0005;
        public static final int angel_editor_religious=0x7f0b0006;
        public static final int angel_editor_stamp=0x7f0b0008;
        public static final int buttonAdd=0x7f0b002d;
        public static final int cameraButton=0x7f0b0010;
        public static final int city=0x7f0b000b;
        public static final int comment=0x7f0b0027;
        public static final int datetime=0x7f0b0025;
        public static final int diary_date=0x7f0b0019;
        public static final int diary_delete_button=0x7f0b001a;
        public static final int diary_edit_button=0x7f0b001b;
        public static final int diary_fragment_sdcard_problem=0x7f0b000f;
        public static final int diary_item_player=0x7f0b0016;
        public static final int diary_item_player_pause=0x7f0b0018;
        public static final int diary_item_player_play=0x7f0b0017;
        public static final int diary_map_button=0x7f0b001d;
        public static final int diary_picture=0x7f0b0014;
        public static final int diary_share_button=0x7f0b001c;
        public static final int diary_text=0x7f0b0015;
        public static final int diary_title=0x7f0b0013;
        public static final int editNoteText=0x7f0b003d;
        public static final int editNoteTitle=0x7f0b003c;
        public static final int editText1=0x7f0b0030;
        public static final int general_item_editor_menu_save=0x7f0b0054;
        public static final int general_item_editor_text=0x7f0b001f;
        public static final int general_item_editor_title=0x7f0b001e;
        public static final int icon=0x7f0b0020;
        public static final int imageView1=0x7f0b0036;
        public static final int label=0x7f0b0021;
        public static final int linearLayout1=0x7f0b002c;
        public static final int main_activity_menu_refresh=0x7f0b0055;
        public static final int mapOverlayButton=0x7f0b002b;
        public static final int mapReportButton=0x7f0b002a;
        public static final int mapview=0x7f0b0028;
        public static final int menu_overlay_angels=0x7f0b0056;
        public static final int menu_overlay_diary=0x7f0b0058;
        public static final int menu_overlay_info=0x7f0b0057;
        public static final int menu_overlay_people=0x7f0b0059;
        public static final int menu_overlay_sleep=0x7f0b005c;
        public static final int menu_overlay_water=0x7f0b005a;
        public static final int menu_overlay_water_hide=0x7f0b005b;
        public static final int menu_report_note=0x7f0b005d;
        public static final int menu_report_problem=0x7f0b005e;
        public static final int message=0x7f0b0043;
        public static final int myLocationButton=0x7f0b0029;
        public static final int name=0x7f0b000a;
        public static final int note_editor_menu_save=0x7f0b005f;
        public static final int overlay_item_viewer_date=0x7f0b003f;
        public static final int overlay_item_viewer_delete=0x7f0b0040;
        public static final int overlay_item_viewer_edit=0x7f0b0041;
        public static final int overlay_item_viewer_linear_layout=0x7f0b003e;
        public static final int pager=0x7f0b0000;
        public static final int phone1=0x7f0b000c;
        public static final int popup_element=0x7f0b000d;
        public static final int profile_username=0x7f0b002f;
        public static final int recordButton=0x7f0b0011;
        public static final int report_dialog_button_angel=0x7f0b004b;
        public static final int report_dialog_button_camera=0x7f0b0045;
        public static final int report_dialog_button_error=0x7f0b0051;
        public static final int report_dialog_button_info=0x7f0b004f;
        public static final int report_dialog_button_mic=0x7f0b0046;
        public static final int report_dialog_button_note=0x7f0b0047;
        public static final int report_dialog_button_sleep=0x7f0b004d;
        public static final int report_dialog_button_water=0x7f0b004a;
        public static final int report_dialog_button_water_hide=0x7f0b0049;
        public static final int sender=0x7f0b0042;
        public static final int share_menu_email=0x7f0b0061;
        public static final int share_menu_facebook=0x7f0b0060;
        public static final int tableRow1=0x7f0b0026;
        public static final int tableRow2=0x7f0b0024;
        public static final int table_message=0x7f0b0023;
        public static final int textView1=0x7f0b000e;
        public static final int textView3=0x7f0b002e;
        public static final int wrapper=0x7f0b0022;
        public static final int writeButton=0x7f0b0012;
    }
    public static final class layout {
        public static final int actionbar_indeterminate_progress=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int angel_editor=0x7f030002;
        public static final int angel_item_layout=0x7f030003;
        public static final int angel_popup=0x7f030004;
        public static final int angels_activity=0x7f030005;
        public static final int diary_fragment=0x7f030006;
        public static final int diary_item_layout=0x7f030007;
        public static final int general_item_editor=0x7f030008;
        public static final int map_fragment=0x7f030009;
        public static final int menu_fragment=0x7f03000a;
        public static final int menu_item=0x7f03000b;
        public static final int message_item_layout=0x7f03000c;
        public static final int my_map_activity=0x7f03000d;
        public static final int my_messages_activity=0x7f03000e;
        public static final int my_profile_activity=0x7f03000f;
        public static final int note_editor=0x7f030010;
        public static final int overlay_item_viewer=0x7f030011;
        public static final int recent_messages_activity=0x7f030012;
        public static final int recent_messages_activity_item=0x7f030013;
        public static final int report_dialog_layout=0x7f030014;
    }
    public static final class menu {
        public static final int angel_editor_menu=0x7f0a0000;
        public static final int general_item_editor_menu=0x7f0a0001;
        public static final int main_activity_menu=0x7f0a0002;
        public static final int map_overlay_menu=0x7f0a0003;
        public static final int map_report_menu=0x7f0a0004;
        public static final int note_editor_menu=0x7f0a0005;
        public static final int share_post=0x7f0a0006;
    }
    public static final class string {
        public static final int angel_editor_address_hint=0x7f07001f;
        public static final int angel_editor_dialog_error=0x7f070024;
        public static final int angel_editor_information_hint=0x7f070023;
        public static final int angel_editor_name_hint=0x7f07001c;
        public static final int angel_editor_passport_text=0x7f070021;
        public static final int angel_editor_phone1_hint=0x7f07001d;
        public static final int angel_editor_phone2_hint=0x7f07001e;
        public static final int angel_editor_religious_text=0x7f070020;
        public static final int angel_editor_stamp_text=0x7f070022;
        public static final int app_name=0x7f070000;
        public static final int buttonMyLocation=0x7f070013;
        public static final int error=0x7f070026;
        public static final int general_item_editor_dialog_error=0x7f07002b;
        public static final int general_item_editor_text_hint=0x7f07002a;
        public static final int general_item_editor_title_hint=0x7f070029;
        public static final int googlemaps_sdk_key=0x7f070012;
        public static final int hello_world=0x7f070004;
        public static final int menu_overlay_title_angels=0x7f070014;
        public static final int menu_overlay_title_diary=0x7f070018;
        public static final int menu_overlay_title_info=0x7f070017;
        public static final int menu_overlay_title_people=0x7f070015;
        public static final int menu_overlay_title_personal=0x7f07002d;
        public static final int menu_overlay_title_sleep=0x7f070019;
        public static final int menu_overlay_title_travelers=0x7f07002c;
        public static final int menu_overlay_title_water=0x7f070016;
        public static final int menu_overlay_title_water_hide=0x7f070028;
        public static final int menu_report_title_add_note=0x7f07001a;
        public static final int menu_report_title_add_problem=0x7f07001b;
        public static final int menu_settings=0x7f070005;
        public static final int refresh=0x7f070027;
        public static final int save=0x7f070025;
        public static final int shit=0x7f070011;
        public static final int title_activity_angel_editor=0x7f07000f;
        public static final int title_activity_angels=0x7f07000b;
        public static final int title_activity_general_item_editor=0x7f070010;
        public static final int title_activity_main=0x7f070006;
        public static final int title_activity_map=0x7f070007;
        public static final int title_activity_messages=0x7f070009;
        public static final int title_activity_note_editor=0x7f07000e;
        public static final int title_activity_people=0x7f07000a;
        public static final int title_activity_profile=0x7f070008;
        public static final int title_activity_recent_messages=0x7f07000d;
        public static final int title_activity_settings=0x7f07000c;
        public static final int title_section1=0x7f070003;
        public static final int title_section2=0x7f070002;
        public static final int title_section3=0x7f070001;
    }
    public static final class style {
        public static final int AppTheme=0x7f090000;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
