/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.shvil.project;

public final class R {
    public static final class anim {
        public static final int animation_enter=0x7f040000;
        public static final int animation_leave=0x7f040001;
        public static final int zoom_enter=0x7f040002;
        public static final int zoom_exit=0x7f040003;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int padding_large=0x7f050002;
        public static final int padding_medium=0x7f050001;
        public static final int padding_small=0x7f050000;
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int black_white_gradient=0x7f020001;
        public static final int bubble_green=0x7f020002;
        public static final int bubble_yellow=0x7f020003;
        public static final int ic_action_location2=0x7f020004;
        public static final int ic_action_map=0x7f020005;
        public static final int ic_action_mapicon=0x7f020006;
        public static final int ic_action_search=0x7f020007;
        public static final int ic_launcher=0x7f020008;
        public static final int ic_menu_location=0x7f020009;
        public static final int ic_menu_location2=0x7f02000a;
        public static final int ic_menu_map_icon=0x7f02000b;
        public static final int ic_shvil=0x7f02000c;
        public static final int ic_water=0x7f02000d;
        public static final int location_button=0x7f02000e;
    }
    public static final class id {
        public static final int EditText01=0x7f090022;
        public static final int EditText02=0x7f090024;
        public static final int EditText03=0x7f090029;
        public static final int EditText04=0x7f09002c;
        public static final int TextView01=0x7f090023;
        public static final int TextView02=0x7f090025;
        public static final int TextView03=0x7f090026;
        public static final int TextView04=0x7f090028;
        public static final int TextView05=0x7f09002a;
        public static final int TextView06=0x7f09002b;
        public static final int buttonAdd=0x7f09001e;
        public static final int cameraButton=0x7f090006;
        public static final int city=0x7f090002;
        public static final int comment=0x7f090018;
        public static final int datetime=0x7f090016;
        public static final int diary_date=0x7f09000c;
        public static final int diary_delete_button=0x7f09000d;
        public static final int diary_edit_button=0x7f09000e;
        public static final int diary_map_button=0x7f090010;
        public static final int diary_picture=0x7f09000a;
        public static final int diary_share_button=0x7f09000f;
        public static final int diary_text=0x7f09000b;
        public static final int diary_title=0x7f090009;
        public static final int editNoteText=0x7f09002e;
        public static final int editNoteTitle=0x7f09002d;
        public static final int editText1=0x7f090021;
        public static final int icon=0x7f090011;
        public static final int imageView1=0x7f090027;
        public static final int label=0x7f090012;
        public static final int linearLayout1=0x7f09001d;
        public static final int mapOverlayButton=0x7f09001c;
        public static final int mapReportButton=0x7f09001b;
        public static final int mapview=0x7f090019;
        public static final int menu_overlay_angels=0x7f090031;
        public static final int menu_overlay_info=0x7f090034;
        public static final int menu_overlay_personal=0x7f090035;
        public static final int menu_overlay_travelers=0x7f090032;
        public static final int menu_overlay_water=0x7f090033;
        public static final int menu_report_note=0x7f090036;
        public static final int menu_report_problem=0x7f090037;
        public static final int message=0x7f090030;
        public static final int myLocationButton=0x7f09001a;
        public static final int name=0x7f090001;
        public static final int note_editor_menu_save=0x7f090038;
        public static final int pager=0x7f090000;
        public static final int phone1=0x7f090003;
        public static final int popup_element=0x7f090004;
        public static final int profile_username=0x7f090020;
        public static final int recordButton=0x7f090007;
        public static final int sender=0x7f09002f;
        public static final int share_menu_email=0x7f09003a;
        public static final int share_menu_facebook=0x7f090039;
        public static final int tableRow1=0x7f090017;
        public static final int tableRow2=0x7f090015;
        public static final int table_message=0x7f090014;
        public static final int textView1=0x7f090005;
        public static final int textView3=0x7f09001f;
        public static final int wrapper=0x7f090013;
        public static final int writeButton=0x7f090008;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int angel_item_layout=0x7f030001;
        public static final int angel_popup=0x7f030002;
        public static final int angels_activity=0x7f030003;
        public static final int diary_fragment=0x7f030004;
        public static final int diary_item_layout=0x7f030005;
        public static final int map_fragment=0x7f030006;
        public static final int menu_fragment=0x7f030007;
        public static final int menu_item=0x7f030008;
        public static final int message_item_layout=0x7f030009;
        public static final int my_map_activity=0x7f03000a;
        public static final int my_messages_activity=0x7f03000b;
        public static final int my_profile_activity=0x7f03000c;
        public static final int note_editor=0x7f03000d;
        public static final int recent_messages_activity=0x7f03000e;
        public static final int recent_messages_activity_item=0x7f03000f;
    }
    public static final class menu {
        public static final int map_overlay_menu=0x7f080000;
        public static final int map_report_menu=0x7f080001;
        public static final int note_editor_menu=0x7f080002;
        public static final int share_post=0x7f080003;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int buttonMyLocation=0x7f060010;
        public static final int googlemaps_sdk_key=0x7f06000f;
        public static final int hello_world=0x7f060004;
        public static final int menu_overlay_title_angels=0x7f060011;
        public static final int menu_overlay_title_info=0x7f060014;
        public static final int menu_overlay_title_personal=0x7f060015;
        public static final int menu_overlay_title_travelers=0x7f060012;
        public static final int menu_overlay_title_water=0x7f060013;
        public static final int menu_report_title_add_note=0x7f060016;
        public static final int menu_report_title_add_problem=0x7f060017;
        public static final int menu_settings=0x7f060005;
        public static final int shit=0x7f06000e;
        public static final int title_activity_angels=0x7f06000b;
        public static final int title_activity_main=0x7f060006;
        public static final int title_activity_map=0x7f060007;
        public static final int title_activity_messages=0x7f060009;
        public static final int title_activity_note_editor=0x7f06000d;
        public static final int title_activity_people=0x7f06000a;
        public static final int title_activity_profile=0x7f060008;
        public static final int title_activity_recent_messages=0x7f06000c;
        public static final int title_section1=0x7f060003;
        public static final int title_section2=0x7f060002;
        public static final int title_section3=0x7f060001;
    }
    public static final class style {
        public static final int AppTheme=0x7f070000;
    }
}
