package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GENERAL_ITEM.
 */
public class GeneralItem {

    private Long id;
    private Byte type;
    private String title;
    private String text;
    private Double longitude;
    private Double latitude;
    private Boolean is_new;

    // KEEP FIELDS - put your custom fields here
    public static enum GeneralItemType {
        GENERAL_ITEM_TYPE_WATER,
        GENERAL_ITEM_TYPE_WATER_HIDE,
        GENERAL_ITEM_TYPE_ERROR,
        GENERAL_ITEM_TYPE_INFORMATION,
        GENERAL_ITEM_TYPE_PEOPLE,
        GENERAL_ITEM_TYPE_SLEEP,
    }
    // KEEP FIELDS END

    public GeneralItem() {
    }

    public GeneralItem(Long id) {
        this.id = id;
    }

    public GeneralItem(Long id, Byte type, String title, String text, Double longitude, Double latitude, Boolean is_new) {
        this.id = id;
        this.type = type;
        this.title = title;
        this.text = text;
        this.longitude = longitude;
        this.latitude = latitude;
        this.is_new = is_new;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Boolean getIs_new() {
        return is_new;
    }

    public void setIs_new(Boolean is_new) {
        this.is_new = is_new;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
