package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SOUND_FILE.
 */
public class SoundFile {

    private Long id;
    /** Not-null value. */
    private String uri;
    private String text;
    /** Not-null value. */
    private java.util.Date date;
    private Float longitude;
    private Float latitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SoundFile() {
    }

    public SoundFile(Long id) {
        this.id = id;
    }

    public SoundFile(Long id, String uri, String text, java.util.Date date, Float longitude, Float latitude) {
        this.id = id;
        this.uri = uri;
        this.text = text;
        this.date = date;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUri() {
        return uri;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Float getLongitude() {
        return longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    public Float getLatitude() {
        return latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
