package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ANGEL.
 */
public class Angel {

    private Long id;
    /** Not-null value. */
    private String city;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String phone1;
    private String phone2;
    private String information;
    private double latitude;
    private double longitude;
    private Boolean passport;
    private Boolean stamp;
    private Boolean religious;
    private Boolean is_new;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Angel() {
    }

    public Angel(Long id) {
        this.id = id;
    }

    public Angel(Long id, String city, String name, String phone1, String phone2, String information, double latitude, double longitude, Boolean passport, Boolean stamp, Boolean religious, Boolean is_new) {
        this.id = id;
        this.city = city;
        this.name = name;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.information = information;
        this.latitude = latitude;
        this.longitude = longitude;
        this.passport = passport;
        this.stamp = stamp;
        this.religious = religious;
        this.is_new = is_new;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPhone1() {
        return phone1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getPhone2() {
        return phone2;
    }

    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getInformation() {
        return information;
    }

    public void setInformation(String information) {
        this.information = information;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Boolean getPassport() {
        return passport;
    }

    public void setPassport(Boolean passport) {
        this.passport = passport;
    }

    public Boolean getStamp() {
        return stamp;
    }

    public void setStamp(Boolean stamp) {
        this.stamp = stamp;
    }

    public Boolean getReligious() {
        return religious;
    }

    public void setReligious(Boolean religious) {
        this.religious = religious;
    }

    public Boolean getIs_new() {
        return is_new;
    }

    public void setIs_new(Boolean is_new) {
        this.is_new = is_new;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
