package com.shvil.project.db;

import com.shvil.project.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private Long id;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private java.util.Date time;
    private Long conversationId;
    private long senderId;
    private long receiverId;
    private Long groupId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MessageDao myDao;

    private User messageSenderId;
    private Long messageSenderId__resolvedKey;

    private User messageReceiverId;
    private Long messageReceiverId__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String message, java.util.Date time, Long conversationId, long senderId, long receiverId, Long groupId) {
        this.id = id;
        this.message = message;
        this.time = time;
        this.conversationId = conversationId;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.groupId = groupId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMessageDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Long getConversationId() {
        return conversationId;
    }

    public void setConversationId(Long conversationId) {
        this.conversationId = conversationId;
    }

    public long getSenderId() {
        return senderId;
    }

    public void setSenderId(long senderId) {
        this.senderId = senderId;
    }

    public long getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(long receiverId) {
        this.receiverId = receiverId;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /** To-one relationship, resolved on first access. */
    public User getMessageSenderId() {
        if (messageSenderId__resolvedKey == null || !messageSenderId__resolvedKey.equals(senderId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            messageSenderId = targetDao.load(senderId);
            messageSenderId__resolvedKey = senderId;
        }
        return messageSenderId;
    }

    public void setMessageSenderId(User messageSenderId) {
        if (messageSenderId == null) {
            throw new DaoException("To-one property 'senderId' has not-null constraint; cannot set to-one to null");
        }
        this.messageSenderId = messageSenderId;
        senderId = messageSenderId.getId();
        messageSenderId__resolvedKey = senderId;
    }

    /** To-one relationship, resolved on first access. */
    public User getMessageReceiverId() {
        if (messageReceiverId__resolvedKey == null || !messageReceiverId__resolvedKey.equals(receiverId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            messageReceiverId = targetDao.load(receiverId);
            messageReceiverId__resolvedKey = receiverId;
        }
        return messageReceiverId;
    }

    public void setMessageReceiverId(User messageReceiverId) {
        if (messageReceiverId == null) {
            throw new DaoException("To-one property 'receiverId' has not-null constraint; cannot set to-one to null");
        }
        this.messageReceiverId = messageReceiverId;
        receiverId = messageReceiverId.getId();
        messageReceiverId__resolvedKey = receiverId;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
