package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DIARY_ITEM.
 */
public class DiaryItem {

    private Long id;
    private Byte type;
    private String titleuri;
    private String text;
    /** Not-null value. */
    private java.util.Date date;
    private Double longitude;
    private Double latitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DiaryItem() {
    }

    public DiaryItem(Long id) {
        this.id = id;
    }

    public DiaryItem(Long id, Byte type, String titleuri, String text, java.util.Date date, Double longitude, Double latitude) {
        this.id = id;
        this.type = type;
        this.titleuri = titleuri;
        this.text = text;
        this.date = date;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getTitleuri() {
        return titleuri;
    }

    public void setTitleuri(String titleuri) {
        this.titleuri = titleuri;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
