package com.shvil.project.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.shvil.project.db.Angel;
import com.shvil.project.db.User;
import com.shvil.project.db.Message;
import com.shvil.project.db.DiaryItem;

import com.shvil.project.db.AngelDao;
import com.shvil.project.db.UserDao;
import com.shvil.project.db.MessageDao;
import com.shvil.project.db.DiaryItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig angelDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig diaryItemDaoConfig;

    private final AngelDao angelDao;
    private final UserDao userDao;
    private final MessageDao messageDao;
    private final DiaryItemDao diaryItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        angelDaoConfig = daoConfigMap.get(AngelDao.class).clone();
        angelDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        diaryItemDaoConfig = daoConfigMap.get(DiaryItemDao.class).clone();
        diaryItemDaoConfig.initIdentityScope(type);

        angelDao = new AngelDao(angelDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        diaryItemDao = new DiaryItemDao(diaryItemDaoConfig, this);

        registerDao(Angel.class, angelDao);
        registerDao(User.class, userDao);
        registerDao(Message.class, messageDao);
        registerDao(DiaryItem.class, diaryItemDao);
    }
    
    public void clear() {
        angelDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        diaryItemDaoConfig.getIdentityScope().clear();
    }

    public AngelDao getAngelDao() {
        return angelDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public DiaryItemDao getDiaryItemDao() {
        return diaryItemDao;
    }

}
