package com.shvil.project.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table WATER.
 */
public class Water {

    private Long id;
    private String title;
    private String text;
    private Double longitude;
    private Double latitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Water() {
    }

    public Water(Long id) {
        this.id = id;
    }

    public Water(Long id, String title, String text, Double longitude, Double latitude) {
        this.id = id;
        this.title = title;
        this.text = text;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
