//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recorder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Devices_media_floppy_icon {
            get {
                object obj = ResourceManager.GetObject("Devices_media_floppy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directoryPicture {
            get {
                object obj = ResourceManager.GetObject("directoryPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap File_Types_MIDI_icon {
            get {
                object obj = ResourceManager.GetObject("File_Types_MIDI_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Flute {
            get {
                object obj = ResourceManager.GetObject("Flute", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GClefPicture {
            get {
                object obj = ResourceManager.GetObject("GClefPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ghostscriptPicture {
            get {
                object obj = ResourceManager.GetObject("ghostscriptPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock__noteDrawer_ {
            get {
                object obj = ResourceManager.GetObject("lock__noteDrawer_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Microphone_icon {
            get {
                object obj = ResourceManager.GetObject("Microphone_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_icon {
            get {
                object obj = ResourceManager.GetObject("Pause_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play_icon {
            get {
                object obj = ResourceManager.GetObject("Play_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72;c;c;c;c;c;c;c;c;
        ///73;c;c;c;c;c;c;c;h;
        ///74;c;c;c;c;c;c;c;u;
        ///75;c;c;c;c;c;c;h;u;
        ///76;c;c;c;c;c;c;u;u;
        ///77;c;c;c;c;c;u;c;c;
        ///78;c;c;c;c;u;c;c;u;
        ///79;c;c;c;c;u;u;u;u;
        ///80;c;c;c;u;c;c;h;u;
        ///81;c;c;c;u;u;u;u;u;
        ///82;c;c;u;c;c;u;u;u;
        ///83;c;c;u;u;u;u;u;u;
        ///84;c;u;c;u;u;u;u;u;
        ///85;u;c;c;u;u;u;u;u;
        ///86;u;u;c;u;u;u;u;u;
        ///87;u;u;c;c;c;c;c;u;
        ///88;h;c;c;c;c;c;u;u;
        ///89;h;c;c;c;c;u;c;u;
        ///90;h;c;c;c;u;c;u;u;
        ///91;h;c;c;c;u;u;u;u;
        ///92;h;c;c;u;c;u;u;u;
        ///93;h;c;c;u;u;u;u;u;
        ///94;h;c;c;u;c;c;c;u;
        ///95;h;c;c;u;c;c;u;u;
        ///96;h;c;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recorderFingering {
            get {
                return ResourceManager.GetString("recorderFingering", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RecorderPicture {
            get {
                object obj = ResourceManager.GetObject("RecorderPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0; 20; 205; 10; 10;
        ///1; 50; 205; 10; 10;
        ///2; 50; 237; 10; 10;
        ///3; 50; 268; 10; 10;
        ///4; 50; 302; 10; 10;
        ///5; 50; 337; 10; 10;
        ///6; 50; 364; 10; 10;
        ///7; 45; 393; 10; 10;.
        /// </summary>
        internal static string recorderPictureHoles {
            get {
                return ResourceManager.GetString("recorderPictureHoles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save1 {
            get {
                object obj = ResourceManager.GetObject("save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_icon {
            get {
                object obj = ResourceManager.GetObject("Stop_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_red_icon {
            get {
                object obj = ResourceManager.GetObject("stop_red_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
